apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: bfoa
version: 0.1.2
tillerVersion: ">=2.5.0"
keywords:
  - test
  - bfoa
home: https://github.com/GuillaumeKG/HelmCharts/bfoa
maintainers:
  - name: Guillaume KG
engine: gotpl

