{{- range $index, $value:=.Values.deployments -}}
{{- if gt $index 0 -}}
---
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "Name of a deployment is mandatory." .name }}
  namespace: {{ include "bfoa.namespace" $ }}
  labels:
    app.kubernetes.io/name: {{ .name }}
{{ include "bfoa.labels" $ | indent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      serviceAccountName: {{ $.Values.uniqueIdentitifier }}-sa
      serviceAccount: {{ $.Values.uniqueIdentitifier }}-sa
    {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      {{- range .containers }}
      - name: {{ .name }}
        image: {{ .image.repository }}:{{ .image.tag }}
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .service.port }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .livenessProbe.path }}
            port: http
        readinessProbe:
          httpGet:
            path: {{ .readynessProbe.path }}
            port: http
        resources:
          {{- toYaml .resources | nindent 12 }}
      {{- end -}}
{{- end -}}