apiVersion: v1
kind: ServiceAccount
metadata:
 name: {{ .Values.uniqueIdentitifier }}-sa
 namespace: {{ include "bfoa.namespace" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: {{ .Values.uniqueIdentitifier }}-role
 namespace: {{ include "bfoa.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces", "events", "replicationcontrollers", "serviceaccounts", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "configmaps"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["list", "get"]
- apiGroups: ["apps"]
  resources: ["controllerrevisions", "statefulsets"]
  verbs: ["list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets", "ingresses"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["replicationcontrollers/scale"]
  verbs: ["get", "update"]
- apiGroups: ["extensions"]
  resources: ["deployments/scale", "replicasets/scale"]
  verbs: ["get", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: {{ .Values.uniqueIdentitifier }}-role-binding
 namespace: {{ include "bfoa.namespace" . }}
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: {{ .Values.uniqueIdentitifier }}-role
subjects:
- namespace: {{ include "bfoa.namespace" . }}
  kind: ServiceAccount
  name: {{ .Values.uniqueIdentitifier }}-sa

# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: admin-{{ .Values.uniqueIdentitifier }}-role
#   namespace: {{ include "bfoa.namespace" . }}
# rules:
# - apiGroups: ["*"]
#   resources: ["*"]
#   verbs: ["*"]


