{{- range .Values.deployments -}}
{{- range .containers -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ include "bfoa.namespace" $ }}
  labels:
    app.kubernetes.io/name: {{ .name }}
{{ include "bfoa.labels" $ | indent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
---
{{ end }}
{{- end }}
